name: Build and deploy Node.js app to Azure Web App - moviesentimentanalyzer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          #cache: 'npm'

      - name: Install and build React frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build
        env:
          CI: false
          REACT_APP_API_URL: https://your-api-url.azurewebsites.net

      - name: Zip build output
        run: |
          cd frontend
          zip -r release.zip build/ startup.sh package.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip build artifact
        run: |
          ls -la  
          unzip release.zip -d frontend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_26E4E6B5FA3C4B1BA2760501CE053CD7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B66FD8A57519450EB1EF5ED415572C4C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D0E23FFA1DEB4B21BA427A6FDC2A4EB1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviesentimentanalyzer'
          slot-name: 'Production'
          package: frontend/build


          
